[cursor]
style = "Beam"

[window]
startup_mode = "Maximized"
dynamic_padding = true
opacity = 1.0
padding = { x = 2, y = 2 }
decorations = "Buttonless"

[font]
normal = { family = "CodeNewRoman Nerd Font" }
bold = { family = "CodeNewRoman Nerd Font" }
italic = { family = "CodeNewRoman Nerd Font" }
size = 14

#[window.dimensions]
#columns = 90
#lines = 25

# Colours (Monokai Charcoal)

# Default Colours
[colors.primary]
background = '#181818'
foreground = '#d8d8d8'

[colors.cursor]
text = '#181818'
cursor = '#d8d8d8'

# Normal colors
[colors.normal]
black   = '#181818'
red     = '#ab4642'
green   = '#a1b56c'
yellow  = '#f7ca88'
blue    = '#7cafc2'
magenta = '#ba8baf'
cyan    = '#86c1b9'
white   = '#d8d8d8'

# Bright colors
[colors.bright]
black   = '#585858'
red     = '#ab4642'
green   = '#a1b56c'
yellow  = '#f7ca88'
blue    = '#7cafc2'
magenta = '#ba8baf'
cyan    = '#86c1b9'
white   = '#f8f8f8'
