theme = "dark_plus"

[editor]
line-number = "relative"
mouse = false
bufferline = "multiple"
color-modes = true

[editor.lsp]
enable = false
auto-signature-help = false
display-signature-help-docs = false
snippets = false

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
insert = "bar"

[keys.insert]
j = {k = "normal_mode"}

[keys.normal]
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
g = {a = "code_action"}
V = ["extend_line_below", "select_mode"]
K = "hover"

[keys.normal.";"]
f = "file_picker"
w = ":w"
q = ":buffer-close!"
e = "reveal_current_file" # Only if is in the branch. Waiting for merge in master
t = { e = ":sh tmux send-keys -t '2' 'mix test' Enter ", r = ":sh tmux send-keys -t '2' 'cargo test' Enter", g = ":sh tmux send-keys -t '2' 'go test ./... -v' Enter", n = ":sh tmux send-keys -t '2' 'yarn test' Enter"}
l = { s = ":lsp-stop", r = ":lsp-restart"}

[editor.explorer]
position = "right"

[editor.statusline]
right = ["version-control", "diagnostics", "selections", "position"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
