#!/bin/sh

current_pane="$(tmux list-panes -F "#{pane_active} #{pane_pid} #{pane_current_command}" | grep "^1" | awk '{print $3}' | tr -d ' ')"

if [ "$current_pane" = "Vim" ] || [ "$current_pane" = "vi" ] || [ "$current_pane" = "nvim" ]; then
  tmux send-keys ":silent ! tmux splitw -h -l 40 -- ~/ayedero/scripts/file_tree " C-r % Enter
fi

if [ "$current_pane" = "hx" ]; then
  tmux send-keys ":sh tmux splitw -h -l 40 -- ~/ayedero/scripts/file_tree" C-r % Enter
fi
