theme = "dracula"

[editor]
evil = true
line-number = "relative"
mouse = false
bufferline = "multiple"
color-modes = true
auto-completion = false

[editor.lsp]
enable = true
snippets = false
display-messages = true
display-inlay-hints = true
auto-signature-help = false
#display-signature-help-docs = false

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
insert = "bar"

[keys.insert]
j = {k = "normal_mode"}
C-n = "signature_help"

[keys.normal]
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
g = {a = "code_action"}
V = ["extend_line_below", "select_mode"]
K = "hover"

[keys.normal.";"]
f = "file_picker"
w = ":w"
q = ":bc"
#e = ":sh zellij run -f -x 10% -y 10% --width 80% --height 80% -- bash ~/ayedero/scripts/yazi-picker.sh"

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

